const products = [
  {
    id: 1,
    image: 'src/assets/images/expresso-tradicional.png',
    types: ['TRADICIONAL'],
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    value: 9.90,
  },
  {
    id: 2,
    image: 'src/assets/images/expresso-americano.png',
    types: ['TRADICIONAL'],
    name: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    value: 9.90,
  },
  {
    id: 3,
    image: 'src/assets/images/expresso-cremoso.png',
    types: ['TRADICIONAL'],
    name: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    value: 9.90,
  },
  {
    id: 4,
    image: 'src/assets/images/expresso-gelado.png',
    types: ['TRADICIONAL', 'GELADO'],
    name: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    value: 9.90,
  },
  {
    id: 5,
    image: 'src/assets/images/cafe-com-leite.png',
    types: ['TRADICIONAL', 'COM LEITE'],
    name: 'Café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    value: 9.90,
  },
  {
    id: 6,
    image: 'src/assets/images/latte.png',
    types: ['TRADICIONAL', 'COM LEITE'],
    name: 'Latte',
    description: 'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    value: 9.90,
  },
  {
    id: 7,
    image: 'src/assets/images/capuccino.png',
    types: ['TRADICIONAL', 'COM LEITE'],
    name: 'Capuccino',
    description: 'Bebida com canela feita de doses iguais de café, leite e espuma',
    value: 9.90,
  },
  {
    id: 8,
    image: 'src/assets/images/macchiato.png',
    types: ['TRADICIONAL', 'COM LEITE'],
    name: 'Macchiato',
    description: 'Café expresso misturado com um pouco de leite quente e espuma',
    value: 9.90,
  },
  {
    id: 9,
    image: 'src/assets/images/mocaccino.png',
    types: ['TRADICIONAL', 'COM LEITE'],
    name: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    value: 9.90,
  },
  {
    id: 10,
    image: 'src/assets/images/chocolate-quente.png',
    types: ['ESPECIAL', 'COM LEITE'],
    name: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    value: 9.90,
  },
  {
    id: 11,
    image: 'src/assets/images/cubano.png',
    types: ['ESPECIAL', 'ALCOÓLICO', 'GELADO'],
    name: 'Cubano',
    description: 'Drink gelado de café expresso com rum, creme de leite e hortelã',
    value: 9.90,
  },
  {
    id: 12,
    image: 'src/assets/images/havaiano.png',
    types: ['ESPECIAL'],
    name: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    value: 9.90,
  },
  {
    id: 13,
    image: 'src/assets/images/arabe.png',
    types: ['ESPECIAL'],
    name: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    value: 9.90,
  },
  {
    id: 14,
    image: 'src/assets/images/irlandes.png',
    types: ['ESPECIAL', 'ALCOÓLICO'],
    name: 'Irlandês',
    description: 'Bebida à base de café, uísque irlandês, açúcar e chantilly',
    value: 9.90,
  },
];

export default products;